name: Daily Current Affairs Scraper

on:
  schedule:
    - cron: '30 2 * * *' # 2:30 AM UTC = 8:00 AM IST
  workflow_dispatch: # Allows manual triggering

jobs:
  scrape-and-post:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Adjust version as needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper script
        env:
          MONGO_CONNECTION_STRING: ${{ secrets.MONGO_CONNECTION_STRING }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          DB_NAME: "mcqwale"
          COLLECTION_NAME: "scraped_url"
        run: |
          python main.py # Replace with your script's filename

      - name: Commit any changes (e.g., updated MongoDB data)
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Update scraped data" || echo "No changes to commit"
          git push
        continue-on-error: true
